array_layout = "Block"
array_width = 120
chain_one_line_max = 240
closure_block_indent_threshold = 0
comment_width = 120
error_on_line_overflow = false
fn_args_density = "Compressed"
fn_call_style = "Block"
fn_call_width = 240
match_block_trailing_comma = true
max_width = 65535
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
use_try_shorthand = true
where_density = "Tall"
where_layout = "Horizontal"
wrap_comments = true
